<?php
/**
 * UsersToGroupTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Scalyr
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Scalyr API
 *
 * You can use the Scalyr API to send and retrieve log data directly from Scalyr servers, as well as manage configuration files. It is usually most convenient to use the Scalyr Agent to send log files, and to view logs on the web site.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Scalyr;

use PHPUnit\Framework\TestCase;

/**
 * UsersToGroupTest Class Doc Comment
 *
 * @category    Class
 * @description Object to add users to group
 * @package     Scalyr
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class UsersToGroupTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "UsersToGroup"
     */
    public function testUsersToGroup()
    {
    }

    /**
     * Test attribute "token"
     */
    public function testPropertyToken()
    {
    }

    /**
     * Test attribute "group_name"
     */
    public function testPropertyGroupName()
    {
    }

    /**
     * Test attribute "user_emails"
     */
    public function testPropertyUserEmails()
    {
    }
}
