<?php
/**
 * ScalyrApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Scalyr
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Scalyr API
 *
 * You can use the Scalyr API to send and retrieve log data directly from Scalyr servers, as well as manage configuration files. It is usually most convenient to use the Scalyr Agent to send log files, and to view logs on the web site.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Scalyr;

use \Scalyr\Configuration;
use \Scalyr\ApiException;
use \Scalyr\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ScalyrApiTest Class Doc Comment
 *
 * @category Class
 * @package  Scalyr
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ScalyrApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addUserToGroup
     *
     * This method adds one or more users to a group..
     *
     */
    public function testAddUserToGroup()
    {
    }
}
